// @flow
export const ENABLE_QUICK_ADMIN_OP = false;
export const SLACK_URL = 'https://coursera.slack.com/messages/makeathon';
export const ENABLE_NON_COURSERA_SIGN_IN = false;
export const DEFAULT_COVER_BG =
  'http://www.webdesignhot.com/wp-content/uploads/2015/11/Abstract-Colorful-Geometric-Shapes-Background-Vector-Illustration.jpg';

export const DEFAULT_CATEGORIES = ['GENERAL'];

// TODO(Audrey): replace with real names
export const COURSERA_NAMES = [
  'Audrey Li',
  'Kalan Porter',
  'Hannah Zhang',
  'Myo Thein',
  'Keeley Hulse',
  'Collene Claborn',
  'Madelyn Tenaglia',
  'Charlene Marini',
  'Alan Wojtowicz',
  'Kim Moyer',
  'Dominick Molter',
  'Sanora Brigance',
  'Sharonda Cordeiro',
  'Camie Banta',
  'Gale Longwell',
  'Lola Vickery',
  'Joanne Ned',
  'Ileana Hults',
  'Susan Cromley',
  'Jung Tutt',
  'Mirella Mcglown',
  'Aurea Eichman',
  'Sherice Devereux',
  'Delores Franceschi',
  'Danika Randall',
  'Nenita Silk',
  'Ettie Napolitano',
  'Roberto Yandell',
  'Lanelle Chesnutt',
  'Dorris Neiman',
  'Laurena Kenner',
  'Barry Glowacki',
  'Christy Yeaman',
  'Natosha Hackler',
  'Macie Tyson',
  'Cherry Wozniak',
  'Percy Old',
  'Johnny Mcelwain',
  'Pearl Tidd',
  'Irena Lamantia',
  'Monnie Skeeter',
  'Shoshana Bodie',
  'Tatyana Gooslin',
  'Ines Brewington',
  'Alycia Ringo',
  'Reta Lastinger',
  'Syreeta Twyman',
  'Hulda Jemison',
  'Wiley Torrain',
  'Brendan Perlman',
  'Eugene Engels',
  'Lavada Carrithers',
  'Apryl Broom',
  'Hortencia Marston',
  'Yi Ricci',
];
